### ISSUE TITLE
How do you customize the help command?

### ISSUE THREAD

**Issue by Onii-Chan-Discord** [freya022/BotCommands#17]
How do you customize the help command, I've read over the docs several and I might've missed if it was documented, but if it isn't, is there a supported way to edit the help command or do I need to fork the repo and make changes?

**Comment by freya022** [comment]
There are two different ways of adding content to the help command:

* One with `TextCommandsBuilder#setHelpBuilderConsumer`, which will let you add more info to the *global* (the one sent in DMs) help embed
* And the other one with `TextCommandsBuilder#disableHelpCommand`, which lets you "override" the behavior of the help command, this is used when a user misuses a command and no fallback method exists for the command

You can get a `TextCommandsBuilder` to configure these in `CommandsBuilder#textCommandBuilder`

You may also join the support server for further discussion

**Comment by Onii-Chan-Discord** [comment]
Ah, thank you! Also thank you for the quick response.
